name: Deploy Express App

on:
  push:
    branches:
      - master  # Change to your default branch if it's not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy to VPS
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}  # Add your SSH password as a secret
      run: |
        sshpass -p "${SSH_PASSWORD}" scp -r ./* $SSH_USERNAME@$SSH_HOST:/root/lazzez-serverapp
        sshpass -p "${SSH_PASSWORD}" ssh $SSH_USERNAME@$SSH_HOST "
          cd /root/lazzez-serverapp &&
          npm install &&
          pm2 restart lazeez-backend || pm2 start server.js --name lazeez-backend
        "
