name: Deploy Express App

on:
  push:
    branches:
      - master  # Change to your default branch if it's not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/private_key
        chmod 600 ~/.ssh/private_key
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Debug SSH Setup
      run: |
        cat ~/.ssh/private_key
        ls -l ~/.ssh/private_key

    - name: Deploy to VPS
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      run: |
        scp -i ~/.ssh/private_key -r ./* $SSH_USERNAME@$SSH_HOST:/root/lazzez-serverapp
        ssh -i ~/.ssh/private_key $SSH_USERNAME@$SSH_HOST "
          cd /root/lazzez-serverapp &&
          npm install &&
          pm2 restart lazeez-backend || pm2 start server.js --name lazeez-backend
        "
